version: '3'
services:
  app:
    container_name: astro-udon-blog
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ../articles/blog:/usr/src/app/src/content/blog